### ISSUE TITLE
Possible Unhandled promise rejection

### ISSUE THREAD

**Issue by kmkrtich** [vinzscam/react-native-file-viewer#113]
After updating targetSdkVersion = 30 and compileSdkVersion = 30 this lib stopped working for me.
I am getting this warning each time I try to open any file (jpg/pdf ...)
Possible Unhandled Promise Rejction (id: 0)
Error: No app associated with this mime type.

ReactNative - 0.63.3 (even with 0.64.2)
react-native-file-viewer - 2.1.4

**Comment by pcprinz** [comment]
same here. I even didn't get the solution from #109 working. Any updates on this since July?

**Comment by vinzscam** [comment]
Hi! There is an extra step specifically required for devices targeting Android 11(API level 30)+. I've updated the [documentation](https://github.com/vinzscam/react-native-file-viewer#extra-step-android-only).
