### ISSUE TITLE
Back button on viewer closes the app

### ISSUE THREAD

**Issue by keponk** [vinzscam/react-native-file-viewer#115]
I can successfully open my files and interacti with the different options on the viewer (share, save, etc), but when I click the 'Back' button on the top left of the viewer (android) or on the viewer or on the home menu (android 'back' arrow) I am sent back to the home screen as if the app has been closed.

It doesn't seem like an error but more like some flag or condition I'm missing. Any tips?

**Comment by vinzscam** [comment]
Hi! Thank you for reporting the issue.

The issue might be related to the configuration of your application.
Have you customized your `AndroidManifest.xml` using something different regarding the launchMode of your main activity (`android:launchMode`)?

Could you share your `AndroidManifest.xml` together with a snippet of your code invoking `react-native-file-viewer`?
