### ISSUE TITLE
version 2.1.4 - crash in iOS 15

### ISSUE THREAD

**Issue by code-by** [vinzscam/react-native-file-viewer#121]
Hello
After updating iOS to 15 me and other users of developing app experience crash while press 'Share' button w/o any error messages (
How to solve this?

**Comment by vinzscam** [comment]
Hi,
I've tried and I couldn't reproducing the issue.
Are you experiencing the issue on some particular iOS device or simulator?
Which type of file are you opening? Could you share a snippet of your code?

**Comment by code-by** [comment]
It is turned out that problem in old version of ReactNativeNavigation
