### ISSUE TITLE
Fileviewer.open not working

### ISSUE THREAD

**Issue by Mdmuzammil16** [vinzscam/react-native-file-viewer#127]

**Comment by franFanton-Crombie** [comment]
Hello , could you fix it?.

**Comment by YTRodi** [comment]
still not working

**Comment by Asad520** [comment]
faced the same problem a couple of times. Rebuilding the app fixed the issue

**Comment by AMINEDGE** [comment]
I have the same problem, on android 12, tries to open the file but the dialog just closes with no error
