### ISSUE TITLE
Open file types docx, pdf, pptx error

### ISSUE THREAD

**Issue by repapa** [vinzscam/react-native-file-viewer#13]
Hi @vinzscam,

I'm using Android Marshmallow Emulator and react-native-document-picker to pick a file which the response is a file URI then I convert it using react-native-get-real-path and the response is a absolute path.

Now when I used react-native-file-viewer I just pass the absolute path on it and it was able to open .jpg(need to pick a photo viewer app) and .txt(html view) but I got an error when I tried to open .docx, .PPTX and .pdf.

I would like to ask for your assistance on this.

FYR.

Below is my code implementation:
![image](https://user-images.githubusercontent.com/19182530/39466035-3d7568d6-4d59-11e8-85a4-93042b4b529f.png)

Below is the attached files:
![image](https://user-images.githubusercontent.com/19182530/39466057-5b4e492c-4d59-11e8-92f2-75081080771e.png)

Below is the logs:
![image](https://user-images.githubusercontent.com/19182530/39466071-76dc2dd0-4d59-11e8-8556-bebda3a790ea.png)

**Comment by vinzscam** [comment]
Hi @repapa!
The problem could be probably related to the Simulator. Sometimes Simulator images don't come with a File Viewer installed. I would recommend you to use [Genymotion](https://www.genymotion.com/fun-zone/), install [Google Play Service](https://www.genymotion.com/help/desktop/faq/#google-play-services) on the Simulator and Download a File Reader app like Google Docs or Google Drive.

**Comment by FRizzonelli** [comment]
@vinzscam I've this problem on real devices. It fails with error `Error: It wasn't possible to detect the type of the file`. I'm passing a _.docx_ file :( Google Drive is installed and other docx works on the device

**Comment by FRizzonelli** [comment]
@vinzscam Found the problem: [here](https://stackoverflow.com/questions/14320527/android-should-i-use-mimetypemap-getfileextensionfromurl-bugs/14321470).
Basically you need to pass an encoded path, otherwise _MimeTypeMap_ won't be able to recognize the type

**Comment by lucasR23** [comment]
> @vinzscam Found the problem: [here](https://stackoverflow.com/questions/14320527/android-should-i-use-mimetypemap-getfileextensionfromurl-bugs/14321470).
> Basically you need to pass an encoded path, otherwise _MimeTypeMap_ won't be able to recognize the type

@FRizzonelli  How did you encode the path ? because i got the same error `Error: It wasn't possible to detect the type of the file` and tried to encode using `encodeURIComponent()` but then i got another error: 
```
Error: Failed to find configured root that contains /content%3A%2F%2Fcom.android.providers.downloads.documents%2Fdocument%2F21
    at index.js:24
    at RCTDeviceEventEmitter.emit (EventEmitter.js:189)
    at MessageQueue.__callFunction (MessageQueue.js:366)
    at MessageQueue.js:106
    at MessageQueue.__guard (MessageQueue.js:314)
    at MessageQueue.callFunctionReturnFlushedQueue (MessageQueue.js:105)
    at debuggerWorker.js:80
```

**Comment by FRizzonelli** [comment]
@lucasR23 I'm using _encodeURI_ from ES5, so it'd be builtin :)
