### ISSUE TITLE
AndroidProtocolHandler: Unable to open content URL (FileNotFoundException: open failed: ENOENT (No such file or directory))

### ISSUE THREAD

**Issue by ruziev-dev** [vinzscam/react-native-file-viewer#130]
I download some files on directory `RNFS.ExternalDirectoryPath`  (`/storage/emulated/0/Android/data/com.myPackage/files`) to provide acces to another applications to my files.
It can be pdf, jpg, mp4, txt, docx, xls and another files.
If I open some of this files by default system programs (pdf or jpg), it works without any problems.
But if I open some files by another side applicatioins (HTML wiever for .txt, or special app for .docx), I see error.

I see that file cant be onpened on link `content://com.maximoclientapp.provider/external_files/fileName.txt`
But If I use Android file explorer and open file from folder `/storage/emulated/0/Android/data/com.myPackage/files` I open all files without problem. How can I open files with correct link?

**Comment by prieyudaarvis** [comment]
how you solve this problem? @ruziev-dev
