### ISSUE TITLE
Cannot display pdf (file is of invalid format)

### ISSUE THREAD

**Issue by kosbog** [vinzscam/react-native-file-viewer#131]
Have the `Cannot display pdf (*file_name* is of invalid format)` error on android. On iOS everything is fine. Also, I did an extra step for android api 30+. 
Maybe its a wrong file path, i have this: `/data/user/0/com.pmgmobileapp/cache/*file_name*.pdf`.
![Screenshot_20220204_160002](https://user-images.githubusercontent.com/16894992/152543415-a7894d7b-d629-4f94-b51f-b2adf748800f.png)

Versions:
```
"react-native-file-viewer": "^2.1.5",
"react-native": "0.66.4",
```
Android:
```
buildToolsVersion = "30.0.2"
minSdkVersion = 21
compileSdkVersion = 30
targetSdkVersion = 30
ndkVersion = "21.4.7075529"
```
Code:
```
const options1: FetchInit = {
  method: 'GET',
  path: `${CACHED_PATH}/${file.name}`
};
const response = await FileSystem.fetch(`${CORE_URL}${url}`, options);
if (response) {
  const fileUri = `${Dirs.CacheDir}/${file.name}`;
  const fileStat = await FileSystem.stat(fileUri);
  await FileViewer.open(`${Dirs.CacheDir}/${file.name}`);
}
```

**Comment by kosbog** [comment]
Already found a source of the problem and it is not related to this viewer.

**Comment by aidab98** [comment]
Hello @kosbog how did you resolve this issue, as I also cannot open pdf links sent in Teams chat in Android?

**Comment by kosbog** [comment]
@aidab98 hi. Sorry, I did not remember what exactly a problem I had. But it was not related to this viewer. I mean, something was wrong with the data that I had (wrong path or something like that, evil was hidden in details).
