### ISSUE TITLE
blank page shown in ios

### ISSUE THREAD

**Issue by MAYILERUMPERUMAL** [vinzscam/react-native-file-viewer#148]
using document picker to picked the file and i click to view the file file is shown but few seconds click the same file file content will be not shown blank white page shown

**Comment by Dhaval1905** [comment]
I am also facing the same issue is IOS.

![simulator_screenshot_413464AC-A0C1-4373-8C25-C1E3B5CC3D8A](https://github.com/vinzscam/react-native-file-viewer/assets/37356596/b0bb46ca-377a-4c99-b5bd-1bafb6b89834)

**Comment by HadiKhalifeh** [comment]
Hello @MAYILERUMPERUMAL , @Dhaval1905  any update ?

**Comment by najamulsaqib** [comment]
Any update @HadiKhalifeh @MAYILERUMPERUMAL @Dhaval1905

**Comment by MAYILERUMPERUMAL** [comment]
@najamulsaqib @HadiKhalifeh 
yes i'm completed this issue, in document picker response data two type of url  one is uri and another one is fileCopyUri
uri is temporavery only using this url to shown documents and images shown  few seconds only so using fileCopyUrl is permanent url so if you are document picker use fileCopUrl .. thank you
