### ISSUE TITLE
Suggestions for other libraries?

### ISSUE THREAD

**Issue by marcato15** [vinzscam/react-native-file-viewer#156]
Given the abandoned nature of this library does anyone have suggestions on other React Native libraries that do this same functionality? Or is there not a currently maintained FileViewer for React Native as of January 2024?

**Comment by vinzscam** [comment]
Hi @marcato15! Just to let you know that I am currently working on the library, addressing some issues and adding support for the new RN architecture, so expect some movement soon.

Is there any specific issue that you would like to point out or that you have experienced?

**Comment by marcato15** [comment]
I actually don't have any features in mind. I just saw the last commit and worried it wouldn't be updated any more. But at this time I don't have any issues.

**Comment by derekchan916** [comment]
@vinzscam Main issue for me is that I'm still unable to get android preview working with .xlsx and .docx. I have the newest version of react-native-file-viewer along with RN v0.73.4. My manifest looks as follows
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <queries>
      <package android:name="com.google.android.apps.docs.editors.docs" /> <!-- package names of Google Docs -->
      <package android:name="com.google.android.apps.docs.editors.sheets" /> <!-- package names of Google Sheets -->
      <package android:name="com.google.android.apps.docs.editors.slides" /> <!-- package names of Google Slides -->
      <intent>
        <action android:name="android.intent.action.VIEW" />
        <data android:mimeType="*/*" />
      </intent>
    </queries> 
...
```

I'm also using RNFS to download the file and then displaying it. 
```
const dest = `${RNFS.DocumentDirectoryPath}/testDoc.xlsx`;
const path = RNFS.CachesDirectoryPath + '/' + encodeURIComponent(dest);

await RNFS.downloadFile({fromUrl: <publicUrl/testDoc.xlsx>, toFile: path}).promise;
await FileViewer.open('file://' + path)

```

It's still saying that mimetype is `No app associated with this mime type`

But if I have google sheets installed it will also say "This file isn't available offline..."

Not sure what I'm doing wrong here, I'll continue to see if there are solutions and update if I find anything.

**Comment by vinzscam** [comment]
alright closing the issue! Feel free to open an issue in case you find anything

**Comment by julian-dotcom** [comment]
Any news on this?

**Comment by Vadko** [comment]
Hi, since this library is no longer maintained I've decided to migrate it on my own: https://github.com/Vadko/react-native-file-viewer-turbo. Enjoy!
