### ISSUE TITLE
iOs - Hide status bar

### ISSUE THREAD

**Issue by paulintrognon** [vinzscam/react-native-file-viewer#18]
Is there a way to hide the status bar while viewing a file on ios?

In my app the status bar is always hidden. When I open a PDF with this modules, the status bar shows up and then stays present in my app after I close the file preview. Any ideas?

Thanks

**Comment by vinzscam** [comment]
Hi @paulintrognon,
The problem should be fixed now.
Upgrade the library to version 1.0.6 and let me know!

**Comment by paulintrognon** [comment]
Thank you so much yeah it's working!

Just one think, didn't you forget to update the `index.d.ts` file to take in account the new options?

**Comment by vinzscam** [comment]
right! I will fix it soon, thank you. In the meanwhile passing a `string` as it was before should work as well (I kept it for retro compatibility).

**Comment by paulintrognon** [comment]
Not sure that worked ; I had an exception after I updated, I had to rewrite the options to the new format for it to work, unsure of why though, as I know nothing about native code and plugins...
