### ISSUE TITLE
Android install and No app associated with this mime type issue

### ISSUE THREAD

**Issue by GavinThomas1192** [vinzscam/react-native-file-viewer#23]
Hey, Firstly, thanks for your hard work! Ios is working beautifully and can't wait to get this up on android..

First issue
The readme installation instructions for android number,
`Copy android/src/main/res/xml/file_viewer_provider_paths.xml to your project res/xml/ directory`
I can't find that path in my project. 
![screen shot 2018-10-30 at 8 15 46 am](https://user-images.githubusercontent.com/28162527/47728811-518a1900-dc1c-11e8-8cdc-d6bfb8efffd2.png)

Second, I can't open a docx on android. I'm assuming due to not completely step four of the installation. But...
`
      //   // const path = // absolute-path-to-my-local-file.
      FileViewer.open(filePath)
        .then(() => {
          console.log('success')
          // success
        })
        .catch(error => {
          // error
          console.log('Error viewing document', error)
        })

`
![screen shot 2018-10-30 at 8 16 00 am](https://user-images.githubusercontent.com/28162527/47728864-66ff4300-dc1c-11e8-831f-6caede6f6bfc.png)

I should also note. When attempting to open a PDF, I get a success and can view the document.

I am not using RNFS but RNfetchBlob as it supports more of what I'm doing with streams. 

UPDATE: It may appear android just doesn't support docx. If you can verify this, lets get a PR stating that in the docs to save newbies like me some time ;).
Thanks!

**Comment by vinzscam** [comment]
Hi,
you can manually create the directory `xml` under `android/app/src/main/res/` and the copy the file into it.

Regarding the docx on android, the issue is probably related to the Simulator that you're using it. Other people had the same issue. I recommend you to use a Simulator with Google Play Services installed, and with a File Reader app like Google Docs or Google Drive.

**Comment by mehdilamrini** [comment]
Hi , 

Same issue here , when we try to open a python file with the option showAppsSuggestions as true ,

Google store is opened and got null in the input text  , the mime is not recognized 

![Uploading Screen Shot 2018-12-21 at 09.13.22.png…]()

**Comment by abhishek-pokhriyal** [comment]
@vinzscam pdf opening fine but can't handle doc on a real android device. please help.

**Comment by AneeqaKhan** [comment]
@vinzscam I am getting this error "No app associated with this mime type" for xls sheet

**Comment by dev-sheng** [comment]
@vinzscam 
nice to meet you.
I really love using this package.
this one is working perfectly in ios. but I'm getting an issue for some types (doc, docx, pptx...) in android
it seems that android doesn't support some mime types.
I want to know how to add additional mime types.

thanks

**Comment by dev-sheng** [comment]
@vinzscam 
I resolved the issue.

**Comment by cliffheart** [comment]
@dev-sheng hi, can you show us how did you solve this problem?

**Comment by smismailalam** [comment]
![image](https://user-images.githubusercontent.com/21331558/137027423-d6ce3654-d8aa-48e3-aeef-c58acab355c1.png)
getting same error  **No app associated with this mime type**

**Comment by brandtiwari007** [comment]
hi, how did you resolve this issue?

**Comment by brandtiwari007** [comment]
<intent-filter>
<action android:name="android.intent.action.VIEW" />
              <data android:mimeType="*/*"/>
<intent-filter>
adding this two line in androidmanifest.xml will solve your issue

**Comment by brandtiwari007** [comment]
<action android:name="android.intent.action.VIEW" />
              <data android:mimeType="*/*"/>

**Comment by gkasireddy202** [comment]
Any solution for XLS. When we are opening XLS file in file viewer we got below error.I am also added below one in androidmanifest.xml file.

<queries>
    <intent>
        <action android:name="android.intent.action.VIEW" />
        <data android:mimeType="*/*" />
    </intent>
    </queries>

**Error: No app associated with this mime type**

**Comment by daniel-keen** [comment]
@dev-sheng why leaving a positive response and not providing the actual solution to the problem? Is it that difficult to share it with the rest of us?

**Comment by vinzscam** [comment]
Hi @thexdd!
Sorry, I missed the latest comments on this issue!
So, regarding the first point (copying `file_viewer_provider_paths.xml`), this is something old which was required before autolinking was introduced. I don't think you need to do this anymore.
The second issue (`No app associated with this mime type`), it could be related to Android devices targeting Android 11+. I've recently upgraded the documentation here https://github.com/vinzscam/react-native-file-viewer#extra-step-android-only

Let me know if this helps! Otherwise feel free to open another issue sharing details about the issueissue, a snippet of your code + information regarding devices or simulators where you are experiencing the issue.

**Comment by daniel-keen** [comment]
@vinzscam Thank you, I really appreciate your reply. It worked. 
By the way, do you know if there is any way of "mapping" a mime type to a different one?
For example, if I want to open json file as if it was "text/plain".

**Comment by Bohda-P** [comment]
@vinzscam issue is still reproduced on Android with file extension .csv. 
How to handle it?

**Comment by vinzscam** [comment]
> @vinzscam issue is still reproduced on Android with file extension .csv. How to handle it?

@Bohda-P do you have any application supporting csv files (e.g. Google Sheets) installed on your device?
Have you listed `text/csv` in your `AndroidManifest.xml` as mentioned in the [documentation]( https://github.com/vinzscam/react-native-file-viewer#extra-step-android-only)?

**Comment by vinzscam** [comment]
> @vinzscam Thank you, I really appreciate your reply. It worked. By the way, do you know if there is any way of "mapping" a mime type to a different one? For example, if I want to open json file as if it was "text/plain".

@thexdd I think it depends on your use case. If you are downloading the file before opening it, saving the file using the `.txt` extension should do the trick.

**Comment by Bohda-P** [comment]
@vinzscam I have to support two different extensions .pdf and .csv so in my AndroidManifest.xml I have type (* / *)

**Comment by UUUUUUII** [comment]
I added ```
<queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:mimeType="*/*" />
        </intent>
    </queries>
``` to my AndroidManifest.xml but I still get 
`No app associated with this mime type`

> 嗨@thexdd！ 对不起，我错过了关于这个问题的最新评论！ 因此，关于第一点（复制`file_viewer_provider_paths.xml`），这是在引入自动链接之前需要的旧内容。我认为你不再需要这样做了。 第二个问题 ( `No app associated with this mime type`)，它可能与针对 Android 11+ 的 Android 设备有关。我最近在这里升级了文档https://github.com/vinzscam/react-native-file-viewer#extra-step-android-only
> 
> 让我知道这是否有帮助！否则，请随意打开另一个问题，分享有关问题问题的详细信息、您的代码片段 + 有关您遇到问题的设备或模拟器的信息。

**Comment by UUUUUUII** [comment]
I added 
`<queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:mimeType="*/*" />
        </intent>
    </queries>`
 to my AndroidManifest.xml but I still get `No app associated with this mime type`

> 嗨@thexdd！ 对不起，我错过了关于这个问题的最新评论！ 因此，关于第一点（复制`file_viewer_provider_paths.xml`），这是在引入自动链接之前需要的旧内容。我认为你不再需要这样做了。 第二个问题 ( `No app associated with this mime type`)，它可能与针对 Android 11+ 的 Android 设备有关。我最近在这里升级了文档https://github.com/vinzscam/react-native-file-viewer#extra-step-android-only
> 
> 让我知道这是否有帮助！否则，请随意打开另一个问题，分享有关问题问题的详细信息、您的代码片段 + 有关您遇到问题的设备或模拟器的信息。

**Comment by UUUUUUII** [comment]
I added
`<queries> <intent> <action android:name="android.intent.action.VIEW" /> <data android:mimeType="*/*" /> </intent> </queries>`
to my AndroidManifest.xml but I still get `No app associated with this mime type`.

> Hi @thexdd! Sorry, I missed the latest comments on this issue! So, regarding the first point (copying `file_viewer_provider_paths.xml`), this is something old which was required before autolinking was introduced. I don't think you need to do this anymore. The second issue (`No app associated with this mime type`), it could be related to Android devices targeting Android 11+. I've recently upgraded the documentation here https://github.com/vinzscam/react-native-file-viewer#extra-step-android-only
> 
> Let me know if this helps! Otherwise feel free to open another issue sharing details about the issueissue, a snippet of your code + information regarding devices or simulators where you are experiencing the issue.

**Comment by Salem-Abderaouf** [comment]
I solve this issue by 
adding 
`<queries>
 <intent> <action android:name="android.intent.action.VIEW" /> <data android:mimeType="*/*" /> </intent> </queries>`
to` androidManifest.xml`
and rebuild the app . 
Also try to install app that read the specific file like csv reader for csv files

**Comment by isaacparsons-dw** [comment]
> I solve this issue by adding `<queries> <intent> <action android:name="android.intent.action.VIEW" /> <data android:mimeType="*/*" /> </intent> </queries>` to` androidManifest.xml` and rebuild the app . Also try to install app that read the specific file like csv reader for csv files

@Salem-Abderaouf  This works great - do you know why it works? It seems to tell android that when met with any type - just view?

**Comment by zahid502** [comment]
> @vinzscam I am getting this error "No app associated with this mime type" for xls sheet

### <queries> 
  <intent> 
     <action android:name="android.intent.action.VIEW" /> 
     <data android:mimeType="*/*" /> 
  </intent> 
</queries>

add these lines of code before **<application** 
to  android/app/src/main/AndroidManifest.xml

**Comment by zahid502** [comment]
> @vinzscam I am getting this error "No app associated with this mime type" for xls sheet

**<queries><intent> <action android:name="android.intent.action.VIEW" /> <data android:mimeType="*/*" /> </intent</queries>**
add these lines of code before <application
to  android/app/src/main/AndroidManifest.xml

**Comment by zahid502** [comment]
> @vinzscam I am getting this error "No app associated with this mime type" for xls sheet

@Salem-Abderaouf code works great.
make sure 
**add these lines of code before <application**
to  AndroidManifest.xml 
otherwise it create **queries** issues during compile time

**Comment by Salem-Abderaouf** [comment]
> > @vinzscam I am getting this error "No app associated with this mime type" for xls sheet
> 
> @Salem-Abderaouf code works great. make sure **add these lines of code before <application** to AndroidManifest.xml otherwise it create **queries** issues during compile time

Thanks bro

**Comment by chenop** [comment]
Im trying to display a pdf file but none of the above helped me until I installed a pdf viewer on the device Im working with...
I wasn't able to catch the error so I dont think I can display some kind of warning to the user - will be happy to hear suggestions.

**Comment by shariqmehmood** [comment]
> Any solution for XLS. When we are opening XLS file in file viewer we got below error.I am also added below one in 

androidmanifest.xml file.
> 
> **Error: No app associated with this mime type**
add 

<img width="1383" height="849" alt="Image" src="https://github.com/user-attachments/assets/6238411d-5ac3-4ccf-9de8-31ef43de64f3" />
