### ISSUE TITLE
Failed to find configured root that contains 

### ISSUE THREAD

**Issue by medelvann** [vinzscam/react-native-file-viewer#27]
**My File Saved In this Path**

path /data/user/0/co.dayamooz.teacher/downloadFiles/other/photo_2018-09-15_17-08-11/downloadFiles/other/photo_2018-09-15_17-08-114
**Error Is**
blob:http://localhost:8081/80bc6725-7ef9-4c84-9f2b-99fce59b0b81:208134 error Error: Failed to find configured root that contains /data/data/co.dayamooz.teacher/downloadFiles/other/photo_2018-09-15_17-08-11/downloadFiles/other/photo_2018-09-15_17-08-11

HELP ME PLEASE

**Comment by rickysullivan** [comment]
Perhaps adding some more info here about how you're using this module as well as some device/dependancy info too.

**Comment by vinzscam** [comment]
Hi,
could you please post your snippet?
Where is your file stored? How have you saved it? Have you used any specific library for doing that?

**Comment by medelvann** [comment]
hi guys , i make a mistake for using package and other problem . no problem. thanks
