### ISSUE TITLE
can not show file in ios 

### ISSUE THREAD

**Issue by medelvann** [vinzscam/react-native-file-viewer#34]
can not show file in ios 9.3 example iphone 4s , and also not show 3gp file in ios later like 12

**Comment by elinahovakimyan** [comment]
Same issue here (using iPhone 6 - 12.1)

**Comment by AboutReact** [comment]
Same Here any update?

**Comment by vinzscam** [comment]
Please, if your are still facing issues, provide your snippet, your RN version and your device/simulator you are using.
