### ISSUE TITLE
Viewer language

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [vinzscam/react-native-file-viewer#38]
When I open a pdf in the left top there is a button with the text "Done" that its like, close or go back, is there anyway I can change that text? I need it in another language, at first I thought it was reading device language, but it isnt

**Comment by vinzscam** [comment]
Hi,
The library uses a native iOS component which rely on the native XCode localizations settings.
To specify a language different than English, you have to specify the supported language(s) in your `Info.plist` file, using `CFBundleLocalizations` or `CFBundleDevelopmentRegion` keys.

More info [here](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html)
