### ISSUE TITLE
Local files

### ISSUE THREAD

**Issue by kdastan** [vinzscam/react-native-file-viewer#4]
Does it work only with local files ? Can I open files by link without downloading ?

**Comment by vinzscam** [comment]
No, this library doesn't have any function to directly open file by link. You can reach the same result combining this library with react-native-fs as described [here](https://github.com/vinzscam/react-native-file-viewer#download-and-open-a-file-using-react-native-fs).

Remember that opening a file using a link means that the file needs to be downloaded anyway, doesn't matter if this process is done under the hood. :)

**Comment by kdastan** [comment]
@vinzscam Got it! Thanks!
