### ISSUE TITLE
App crash after viewer is dismissed

### ISSUE THREAD

**Issue by minhanhnguyen2196** [vinzscam/react-native-file-viewer#41]
Hi, thanks for the library
I'm facing this issue:  
When the user goes back from the viewer app (the app that was used to open the file) to the current app using the Back Button on Android, the current app crashes

Help please!

**Comment by vinzscam** [comment]
Hi,
could you please provide more information? (like the error you're getting and a snippet of your code).
Otherwise it would be very hard to understand what is going on

**Comment by minhanhnguyen2196** [comment]
oh sorry, it was my bad. I copied the file_viewer_provider_paths.xml file to the wrong folder xD

**Comment by isot1990** [comment]
Hello there,

First of all thanks for the library. It works perfect. But problem is same with here. When I press back button after open document, app crash and gives following error:

![image](https://user-images.githubusercontent.com/24360287/55758225-caf52580-5a5e-11e9-9fc0-babd83343f6b.png)

and my simple code:

 FileViewer.open(path)
           .then(() => {
              
           })
           .catch(error => {
              
           });
