### ISSUE TITLE
Edit Interactive PDFs ?

### ISSUE THREAD

**Issue by JeremyBradshaw7** [vinzscam/react-native-file-viewer#42]
I'm opening some interactive PDFs through the file-viewer, and it does allow edits, and enabled the share options. Only problem is if I then save to file system, send to mail, etc, only the base PDF is saved/sent, without any input content (on ios at least). Perhaps as this is called a file "viewer" I'm hoping for too much, but can anything be done? I thought this package was just invoking whatever native file app is registered for a filetype, if that allows edit & save why wouldn't that work? Is there an option to open a file in non-read-only mode?

**Comment by vinzscam** [comment]
Hi,
if the pdf editor doesn't have a "Save as" option, it would be hard to implement this feature.
Unfortunately we're beyond the capabilities of this library.
