### ISSUE TITLE
Can not preview the files in iOS ? 

### ISSUE THREAD

**Issue by bhoomesh950** [vinzscam/react-native-file-viewer#44]
i am new to react-native i unable to preview the files after getting Uri path please help me 
  
`DocumentPicker.show({
      filetype: [DocumentPickerUtil.allFiles()],
    },(error,res) => {`  

      console.log(
        res.uri,
        res.type, // mime type
        res.fileName,
        res.fileSize
     );
      if(res) {
        FileViewer.open(res.uri)
        .then(() => {

          console.log("Success")

        })
        .catch(_err => {

          console.log("Error")
        });
      }

      
    });
  }`

![Simulator Screen Shot - iPhone X - 2019-03-22 at 12 32 23](https://user-images.githubusercontent.com/20543788/54806008-c4b12c00-4c9e-11e9-81cc-8b3b56306012.png)
`2019-03-22 14:54:12.125034+0530 D_I_Picker[21219:7357050] [default] QLUbiquitousItemFetcher: <QLUbiquitousItemFetcher: 0x283e85ae0> could not create sandbox wrapper. Error: Error Domain=NSPOSIXErrorDomain Code=2 "couldn't issue sandbox extension com.apple.quicklook.readonly for '/file:/private/var/mobile/Containers/Data/Application/8B1B80D1-96E0-4415-9C82-7F0BC1EB4357/tmp/org.reactjs.native.example.D-I-Picker-Inbox/Jan%20to%20Feb%2021%20st%20stmt.pages': No such file or directory" UserInfo={NSDescription=couldn't issue sandbox extension com.apple.quicklook.readonly for '/file:/private/var/mobile/Containers/Data/Application/8B1B80D1-96E0-4415-9C82-7F0BC1EB4357/tmp/org.reactjs.native.example.D-I-Picker-Inbox/Jan%20to%20Feb%2021%20st%20stmt.pages': No such file or directory} #PreviewItem`

**Comment by m4rcoperuano** [comment]
Getting the same error here. It was working before... I wonder if it's caused by iOS 12?

**Comment by Sommerfeld** [comment]
Came across this issue, too. Turned out the file didn't exists at this path anymore because I stored the absolute url but the directory changes on every app start. Maybe someone has the same issue.

https://stackoverflow.com/questions/47864143/document-directory-path-change-when-rebuild-application

**Comment by m4rcoperuano** [comment]
I should update on how I fixed this. I found that RN file viewer uses the file extension to preview the downloaded file - it doesn’t read the mime type (or maybe it does, idk). I just know I fixed this by making sure the saved file name had the extension in the name

**Comment by TalMars** [comment]
@bhoomesh950 use this solution:
`const decUrl = decodeURI(content.uri).replace('file://', '')`
**content.uri** - uri from DocumentPicker

**Comment by joramirezStackit** [comment]
I think I found the problem, in my case I had something like this "%20" (seems like an space) in the path I was using and I did something like this uri.replace('file://', '').replaceAll('%20', ' ') and it worked
