### ISSUE TITLE
Failed to open pdf file in android

### ISSUE THREAD

**Issue by gomezkitty17** [vinzscam/react-native-file-viewer#47]
Hi,

We were trying to open a pdf file stored in a local file using android emulator.
The file was downloaded using RNFS and stored in document directory path.
In order to fetch the file , we've used `${RNFS.DocumentDirectoryPath}` + "/" + "artworkId=28960045relMedia=43381lang=EN.pdf and in the console the value of it is
 "/data/user/0/<appname>/files/artworkId=28960045relMedia=43381lang=EN.pdf".  However it doesn't open the file and instead it throws an error : Failed to find configured root that contains /data/data/<appname>/files/artworkId=28960045relMedia=43381lang=EN.pdf
Can you advise on how to fix the issue or if we did something wrong in using the module?
Thanks

**Comment by vinzscam** [comment]
Hi, could you please post a snippet of your code?

**Comment by anrajain** [comment]
I am facing the same issue.

` filepath = /data/user/0/<DIRECORTY>/files/Screenshot 2019-06-26 at 13.29.20.png`

`Error = Failed to find configured root that contains `

my code is 

```
return getFile(uri, filename).then(file => {
    FileViewer.open(file)
      .then(() => {})
      .catch(error => {
        debugger;
        console.log(error);
      });
  });

const getFile = (uri: string, filename: string) => {
  let dirs = RNFetchBlob.fs.dirs;
  return RNFetchBlob.config({
    path: `${dirs.DocumentDir}/${filename}`
  })
    .fetch("GET", Config.API_URL + uri, {
      Authorization: `Bearer ${token}`
    })
    .then(res => res.data)
    .catch(err => {
      const errMessage = getErrorMessage(err);
      return errMessage;
    });
};
```

**Comment by anrajain** [comment]
found the solution:

we need to add these two things for android. 

<img width="927" alt="Screenshot 2019-07-03 at 13 51 17" src="https://user-images.githubusercontent.com/45871292/60589388-b1335800-9d99-11e9-9eed-60c650ea3722.png">

I did automatic installation but still these files where not added automatically. so i manually added them. 

for more details , please refer https://github.com/vinzscam/react-native-file-viewer/blob/master/README.md
