### ISSUE TITLE
Error when closing opened file

### ISSUE THREAD

**Issue by tmmgn** [vinzscam/react-native-file-viewer#48]
Opening file working just fine, but when i close any file, i get this error
![photo_2019-04-29_10-10-06](https://user-images.githubusercontent.com/11463030/56880857-089a0c80-6a67-11e9-864d-6a74d4f1e411.jpg)
this happens because this package and react-native-awesome-card-io using the same request codes

**Comment by vinzscam** [comment]
Hi,
this problem should be now fixed in `v1.0.15`.
Let me know.

**Comment by tmmgn** [comment]
its fixed now, thank you
