### ISSUE TITLE
"Save to Files" does not work

### ISSUE THREAD

**Issue by fubar** [vinzscam/react-native-file-viewer#53]
Hi @vinzscam, first off, thanks for this library! Very useful and works very well for my use case.

One thing that is not working for me is the Save to File option from the context menu: When viewing a file, I press the export button (arrow coming out of the box icon in the upper right corner, next to the filename); the context menu shows up as expected; when I press Save to Files, the context menu disappears as expected, and a blank/white view slides in from the bottom of the screen and then immediately disappears again. No error seems to be thrown and nothing else happens. Other menu options such as Print seem to work fine (I haven't tried actually printing but the Printer Options dialog comes up as expected).

I didn't find any mention of this in the docs and in existing issues. Any ideas?

Thanks!

**Comment by fubar** [comment]
It looks like it only does not work in the simulator. On an actual device it works as expected.

**Comment by arjendevos** [comment]
I got the same issue, but on a real device
