### ISSUE TITLE
Can't show file from the internet

### ISSUE THREAD

**Issue by XEmAX32** [vinzscam/react-native-file-viewer#55]
Hello guys, I'm trying to preview a file which is served from my server. 
If I open the url in the browser I can see the preview, but if I try to open it using react-native-file-viewer it doesn't show anything.
I already tried to preview another file from the internet which wasn't from my server and it worked well.
To serve the file from server I used
`res.sendFile(result[0].path, {root: '.'});`
from nodejs express, and to preview it:
`FileViewer.open('http://'+this.props.route+'?read=true').catch(error => console.log(error));`
where this.props.route is the actual route

**Comment by vinzscam** [comment]
Please read the documentation. `FileViewer.open` permits to only open a local file. [Here](https://github.com/vinzscam/react-native-file-viewer#download-and-open-a-file-using-react-native-fs) is described how to do if your file resides on a remote server.

**Comment by imbudhiraja** [comment]
@vinzscam I'm getting this error while showing file from local path after downloading via `react-native-fs`.


**Error** 
```
 [default] QLUbiquitousItemFetcher: <QLUbiquitousItemFetcher: 0x600000b435c0> could not create sandbox wrapper. Error: Error Domain=NSPOSIXErrorDomain Code=22 "couldn't issue sandbox extension com.apple.quicklook.readonly for '/Users/manishbudhiraja/Library/Developer/CoreSimulator/Devices/9EB6CDCA-9E6C-4361-9E30-B32760056FCE/data/Containers/Data/Application/6B72C01D-86D9-4A59-9FA2-069C9FF2F4D5/Documents/temporaryfile.pdf': Invalid argument" UserInfo={NSDescription=couldn't issue sandbox extension com.apple.quicklook.readonly for '/Users/manishbudhiraja/Library/Developer/CoreSimulator/Devices/9EB6CDCA-9E6C-4361-9E30-B32760056FCE/data/Containers/Data/Application/6B72C01D-86D9-4A59-9FA2-069C9FF2F4D5/Documents/temporaryfile.pdf': Invalid argument} #PreviewItem
```


**SAMPLE CODE**
import FileSystem from "react-native-fs";
import FileViewer from "react-native-file-viewer";

      const url =
        "https://www.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf";
      const localFile = `${FileSystem.DocumentDirectoryPath}/temporaryfile.pdf`;

      const options = {
        fromUrl: url,
        toFile: localFile
      };
      try {
        await FileSystem.downloadFile(options);

        FileViewer.open(localFile, {
          displayName: "Manish",
          showOpenWithDialog: true,
          showAppsSuggestions: true
        });
      } catch (e) {}


Can you please help me in fixing this. Thanks

**Comment by vinzscam** [comment]
I think you forgot to add `.promise`:

```
await FileSystem.downloadFile(options).promise;
```
