### ISSUE TITLE
X-code build fails - React/RCTBridgeModule.h file not found

### ISSUE THREAD

**Issue by m-ajay** [vinzscam/react-native-file-viewer#62]
X-code version: 10.3
React native version: 0.59.8
When building I'm getting an error
```
Lexical or Preprocessor Issue Group
/node_modules/react-native-file-viewer/ios/RNFileViewerManager.h:2:9: 'React/RCTBridgeModule.h' file not found
```

**Comment by vinzscam** [comment]
Have you tried running `cd ios && pod install` ?

**Comment by lucasriondel** [comment]
Same here, pod is installed after linking, but React/RCTBridgeModule.h isn't found.

**Comment by lucasriondel** [comment]
I was able to make it work by doing `yarn add react-native-file-viewer` (do **NOT** do a `react-native link` afterwards), add `https://github.com/vinzscam/react-native-file-viewer#download-and-open-a-file-using-react-native-fs` in the `Podfile` and then a `pod install` in the `ios/` folder did the trick, using RN 0.59.10.

**Comment by elourenco** [comment]
I also have the same problem, I'm using react-native: 0.61.2

**Comment by SelvaraniAlagumuthu** [comment]
Same here, how to resolve this?.. any one resolved this issue?..

**Comment by vinzscam** [comment]
@elourenco  and @SelvaraniAlagumuthu have you tried running `cd ios && pod install`? `react-native link` is not required since RN 0.60.

**Comment by lucasriondel** [comment]
I was able to make it work by doing yarn add react-native-file-viewer (do NOT do a react-native link afterwards), add pod 'RNFileViewer', :path => '../node_modules/react-native-file-viewer' in the Podfile and then a pod install in the ios/ folder did the trick, using RN 0.59.10.
