### ISSUE TITLE
on ios files are opened, but immediately closed themselves

### ISSUE THREAD

**Issue by tosh17** [vinzscam/react-native-file-viewer#63]
On Android all work fine.
But when i open file on ios - it opens for a split second and then closes itself. There are no errors in the logs

**Comment by lucasriondel** [comment]
Same here. RN 0.61

**Comment by vinzscam** [comment]
Can you send a snippet of your code?

**Comment by tosh17** [comment]
I solved the problem. As far as I understand under ios, you are calling a modal window, which conflicts with my code. I made a delay(300ms) to start the opening of the  file so that my modal windows managed to close correctly

**Comment by cengit** [comment]
it's not a good idea, adding delay before opening file, do you have better solution?

**Comment by cengit** [comment]
I can reproduce this issue and use this **onDismiss** method can avoid the file-viewer window automatically close  immediately

`
import React, {PureComponent, Component} from 'react';
import {Platform, Image, Text, View, TouchableWithoutFeedback, Dimensions, StyleSheet} from 'react-native';
import Modal from 'react-native-modal';
import FileViewer from 'react-native-file-viewer';
import RNFetchBlob from 'rn-fetch-blob';
export default class TestScreen extends PureComponent {
  constructor(props) {
    super(props);
    this.tabIndex = [];
    this.state = {
      isFileFetching: false
    }
  }

  render() {
    return <>
      <Modal isVisible={this.state.isFileFetching}>
        <View>
          <ActivityIndicator color={spinnerColor} size={size} />
        </View>
      </Modal>
      <TouchableWithoutFeedback onPress={()=>{
        this.setState({isFileFetching:true});

        const filePath = downloadsPath.concat('/', fileName);
        RNFetchBlob.config({path: filePath}).fetch('GET', 'https://xxxx.com/yyy.pdf')
        .then(() => {
          FileViewer.open(filePath, {
            showOpenWithDialog: true, 
            onDismiss:()=>this.setState({isFileFetching: false})
          }).catch((error) => {
            this.setState({ isFileFetching: false });
          });
        })
      }}><Text>download and open </Text></TouchableWithoutFeedback>
    </>
  }
}
`


I assume you also use the react-native-modal for the downloading spinner, I don't know if there is some conflicts between react-native-modal and react-native-file-viewer, if you FileViewer.open() right after setting isVisible=false, the FileViewer will be close automatically. 

you can use the delay(300ms) or close the spinner in onDismiss callback function. I think the last one is better

**Comment by yiheinchai** [comment]
I have the same issue. I am using `react-native-modal` and using the `onModalHide` handler to call `FileViewer.open` and yet it still occurs...I am somewhat reluctant to use setTimout as the timeout might not be enough if the user's iPhone lags in closing the modal.

**Comment by DhruvKalpeshThakar** [comment]
export const downloadSalarySlip = (request) => async (dispatch) => {
  try {
    const userinfo = await AsyncStorage.getItem('LoginData');
    const token = JSON.parse(userinfo)?.token;

    const response = await makeAPIRequest({
      method: GET,
      url: `${api.downloadSalarySlipApi}?user_id=228`,
      headers: {
        'Content-Type': 'application/pdf',
        Authorization: `Bearer ${token}`,
      },
      responseType: 'arraybuffer',
    });

    if (response?.data) {
      const filePath = `${RNFS.DocumentDirectoryPath}/SalarySlip_${Date.now()}.pdf`;
      console.log('File path:', filePath);

      const buffer = Buffer.from(response.data);
      await RNFS.writeFile(filePath, buffer.toString('base64'), 'base64');
      console.log('File saved successfully at:', filePath);

      // Introduce a delay of 300ms before opening the file
      setTimeout(() => {
        FileViewer.open(filePath, { type: 'application/pdf' })
          .then(() => {
            console.log('PDF opened successfully!');
            if (request.onSuccess) request.onSuccess(filePath);
          })
          .catch((error) => {
            console.error('Error opening PDF:', error);
            if (request.onFail) request.onFail('Error opening PDF');
          });
      }, 300); // 300ms delay
    } else {
      console.error('No data in API response');
      if (request.onFail) request.onFail('No data in API response');
    }
  } catch (error) {
    console.error('Error downloading salary slip:', error);
    if (request.onFail) request.onFail(error.message);
  }
};


I have tried adding delay of 300ms , Did @tosh17 told something like this ? As Its not working.
