### ISSUE TITLE
The project 'ReactNative' cannot be referenced. RNFileViewer in VisualStudio2019			

### ISSUE THREAD

**Issue by SelvaraniAlagumuthu** [vinzscam/react-native-file-viewer#66]
Hi,
I want to do show file in my react-native application with uwp. so i installed this package to my react-native winows app. after installation i linked this to my app via visual studio. After add this .csprojt , under refernce i got the warning symbol and also got the message as "Warning	The project 'ReactNative' cannot be referenced.	RNFileViewer" in VisualStudio2019. my react-native project version is 0.59.0 and react-native-windows --template vnext version also 0.59.0. Could you please tell how to resolve this.

**Comment by vinzscam** [comment]
Hi,
unfortunately I can't help with the issue.
Maybe @geweald might help you, since he introduced the support to the Windows Platform.

**Comment by vinzscam** [comment]
@SelvaraniAlagumuthu have you solved this specific issue?

**Comment by AhmedMustafa505** [comment]
How could you solve this issue, because I still have it with latest version of RNW and react-native-file-viewer
