### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by sadikyalcin** [vinzscam/react-native-file-viewer#69]
Cannot get it working with expo 36. Removing `node_modules` and yarn.lock file is not helping.

`import FileViewer from 'react-native-file-viewer';` => `Invariant Violation: Native module cannot be null.`

**Comment by gabgagnon** [comment]
Can you tell your solution?

**Comment by sadikyalcin** [comment]
> Can you tell your solution?

Solution is to eject expo. This module is native so it won't work with expo.
