### ISSUE TITLE
Warning Sending RNFileViewerDidDismiss with no listeners registered

### ISSUE THREAD

**Issue by MakhouT** [vinzscam/react-native-file-viewer#71]
When 'fake dismissing', meaning try to close the file with swipe down, but in the end not closing it and bringing it back up. I am getting a warning.

I've tested this on a physical iPad Pro 10.5 inch, with iOS 13.1.2

I've included a GIF
![bug](https://user-images.githubusercontent.com/3041165/72980580-28cee000-3ddb-11ea-9a91-da1b34543cbb.gif)

**Comment by DonovanDeSmedt** [comment]
Same issue here!
Tested on iPad mini, iOS 13.3

**Comment by vinzscam** [comment]
Hi,
it should be fixed now in `v2.0.2`

**Comment by MakhouT** [comment]
Thanks will test it out!
