### ISSUE TITLE
error: cannot find symbol  

### ISSUE THREAD

**Issue by govind1530** [vinzscam/react-native-file-viewer#75]
contentUri = FileProvider.getUriForFile(getCurrentActivity(), authority, newFile);
                                 ^
  symbol:   method getUriForFile(Activity,String,File)
  location: class FileProvider

**Comment by vinzscam** [comment]
Which RN version are you using?

Does your `gradle.properties` contain the following?

```
android.useAndroidX=true
android.enableJetifier=true
```
