### ISSUE TITLE
File opens with just file name.

### ISSUE THREAD

**Issue by divyanshunegi** [vinzscam/react-native-file-viewer#76]
FileViewer.open method works fine if I opens a file for the first time, but if i open it again after some time it just shows the file name in the middle where content should be displayed

**Comment by AboutReact** [comment]
Any Update on that? I am using iOS 11
![iPhone 11 - 2020-05-01 at 19 39 23](https://user-images.githubusercontent.com/54550555/80811410-7bdadf00-8be3-11ea-9e9d-86a56dd7b4b0.png)

**Comment by vinzscam** [comment]
Are you sure this issue is not related to the code you use to download your file? Can you provide a snippet of your code?

**Comment by AboutReact** [comment]
@vinzscam Thank you for your reply. I have found the solution for that. The solution was to remove the 'file:///' prefix and then pass the URL.

**Comment by vinzscam** [comment]
I see, thanks for sharing.
I will make sure that the library handles this automatically.
