### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by amyblais** [vinzscam/react-native-file-viewer#79]
Thanks for sharing this project! We have added your library in the Mattermost mobile app https://github.com/mattermost/mattermost-mobile/blob/master/package.json#L47.

Would you consider adding a license, such as a MIT or an Apache 2.0 license?

If you use a license it would make it easy to add your work to other open source projects, and we'd love to keep your work in ours.

Thanks kindly for your consideration and let me know if you have any questions!

Please see more context here: https://github.com/mattermost/mattermost-mobile/pull/4357#pullrequestreview-419660531.

**Comment by vinzscam** [comment]
Hi @amyblais! The project was supposed to be released under `MIT` license (as listed in the `package.json`) but somehow I've forgot to add the LICENSE file. It's now fixed.

Thanks for pointing this out. 🙂
