### ISSUE TITLE
Suggestion: Improve README

### ISSUE THREAD

**Issue by lucaslovato** [vinzscam/react-native-file-viewer#81]
# Add screenshots to the README
- One nice suggestion to attract people is adding screenshots to the README;
- With that people will see the package behavior and downloads/stars will increase.

:)

**Comment by vinzscam** [comment]
Thanks @lucaslovato for the suggestion :)
Unfortunately I usually don't pay attention to stars, since they don't pay my bills 😅
But it's definitively a good tip, since it could help people choosing the right library according to their needs.
I will do that!

**Comment by vinzscam** [comment]
Closed by #88
