### ISSUE TITLE
null is not an object (evaluating 'RNFileViewer.open')

### ISSUE THREAD

**Issue by Blackoutseeker** [vinzscam/react-native-file-viewer#82]
I am getting this error when i try to open an PDF file on the user's Android. This is a native lib? Cuz i'm using Expo...

**Comment by skurpi** [comment]
I'm getting this as well. Is there any documentation for how to use this with Expo? Any differences worth knowing about?

**Comment by willnaoosmit** [comment]
Try linking it.

**Comment by Blackoutseeker** [comment]
My React Native CLI have auto linking.

**Comment by vinzscam** [comment]
Hi @Blackoutseeker. In your case, you need to eject your expo project, switching to the [Bare workflow](https://docs.expo.io/bare/customizing/).
