### ISSUE TITLE
How I can open file .glb or .glTF on Android

### ISSUE THREAD

**Issue by rgazeredo** [vinzscam/react-native-file-viewer#83]
Does anyone know how I can use FileViewer to open a .glb or .glTF file on android?

**Comment by vinzscam** [comment]
Hi, I guess you need to have a specific app capable of opening that kind of files. Unfortunately I can't help so much, since this goes outside the scope of this project. Good luck!

**Comment by smanojarun** [comment]
https://medium.com/@linjunghsuan/a-simple-way-to-use-native-ar-viewer-in-react-native-18304bc6c799

this article would help those who want to open GLB file URL
