### ISSUE TITLE
Android can't open file

### ISSUE THREAD

**Issue by BertoGz** [vinzscam/react-native-file-viewer#85]
I get this error message. "Error: Failed to find configured root that contains /file:/storage/emulated/0/Android/data/..."
the Uri is valid, and it works on ios.

I tried the automatic install of this package, then I did manual. no luck.
anyone have experience with something like this?

**Comment by KuriaMacharia** [comment]
Try opening the project from 'open existing project' instead of 'recent projects'. This will allow you to verify the project is the same uri.

**Comment by vinzscam** [comment]
Hi @BertoGz. Could you share your snippet of code?  Is the file already on your device? How are you selecting which file you want to open? The file path `/file:/storage/...` looks definitively wrong...

**Comment by BertoGz** [comment]
@vinzscam   Hello!  so I am combining libraries and using react-native-image-crop-picker to select an image.  I pass the URI from the image into the file-viewer and it does work on IOS but android has "Error: Failed to find configured root that contains" message.  here is a snippet of my code   `export const viewFile = ({ fileUri, remote = false, setImageLoading }) => {
    if (!remote) {
        let uri = fileUri;

        if (Platform.OS === 'ios') {
            uri = fileUri.replace('file://', '');
        }

        if (Platform.OS === 'android') {
            const path = uri; //`${RNFS.CachesDirectoryPath}/${uri}`;

            FileViewer.open(path)
}`

**Comment by vinzscam** [comment]
Can you share more? How is `fileUri` created? How do you use `react-native-image-crop-picker`?

**Comment by vinzscam** [comment]
Hi @BertoGz. I was able to reproduce the issue. It should be now fixed. Try to download version `2.1.2` and let me know.

**Comment by oferRounds** [comment]
@BertoGz @vinzscam – have you found a solution? Facing the same issue, using the latest version (`2.1.4`)

**Comment by oferRounds** [comment]
@vinzscam – I’ve followed this example: https://github.com/vinzscam/react-native-file-viewer#open-a-file-from-android-assets-folder

On iOS it works great, but on Android I get the aforementioned error

**Comment by vinzscam** [comment]
Hi @oferRounds,
the example you're following, refers only to files in your Android assets folder. How have you included your files? Have you created the assets folder through Android Studio? Is your asset folder under `android/app/src/main/assets`?
