### ISSUE TITLE
Unable to open file in iOS

### ISSUE THREAD

**Issue by Vincenttbk** [vinzscam/react-native-file-viewer#87]
Hi I am having an issue with iOS

Below is my code snippet
`		
                let imageDate = `BASE64_DATA`
                let fileName = 'hello.pdf';
		let imagePath = `${RNFS.TemporaryDirectoryPath}/${fileName}`;
		
		RNFS.writeFile(imagePath, imageData, 'base64').then(() => {
				FileViewer.open(imagePath)
					.then(() => {
						// success
						console.log('========== image opened');
					})
					.catch((error) => {
						// error
						console.log('========== image open error', error);
					});
			} 
		});
`

It is working on a clean project, but after integrating it to my own project, QuickLook is not showing. Is there any possible reason why it is not working in my own project? e.g. permission? or am I missing something?

It went into the writeFile clause but both console.log did not appear.

Thank you in advance!

**Comment by Vincenttbk** [comment]
More information, I've try doing NSLog, and it seems like Im able to call the Open function in Objc, but just it doesnt call the 
**presentViewController** function

`RCT_EXPORT_METHOD(open:(NSString *)path invocation:(nonnull NSNumber *)invocationId
    options:(NSDictionary *)options)
{
//I've reached the function
    NSString *displayName = [RCTConvert NSString:options[@"displayName"]];
    File *file = [[File alloc] initWithPath:path title:displayName];

    QLPreviewController *controller = [[CustomQLViewController alloc] initWithFile:file identifier:invocationId];
    controller.delegate = self;

    typeof(self) __weak weakSelf = self;
    [[RNFileViewer topViewController] presentViewController:controller animated:YES completion:^{ 
        [weakSelf sendEventWithName:OPEN_EVENT body: @{@"id": invocationId}]; //Seems like i wont reach here
    }];
}`

**Comment by vinzscam** [comment]
Hi @Vincenttbk. Could you tell me more about the navigation library you are currently using it? Have you tested on Android?

**Comment by Vincenttbk** [comment]
Hi @vinzscam , we are using the react navigation library.

Did a bit more digging, it seems like this function returns a nil in the iOS code

`+ (UIViewController*)topViewController {
    return [self topViewControllerWithRootViewController:[UIApplication sharedApplication].keyWindow.rootViewController];
}`

**Comment by MayurRaval** [comment]
Hi, Same issue with me. Not working for iOS, but working for Android. In iOS, It's opening Quicklook for second and close instantly.

**Comment by vinzscam** [comment]
Thanks @Vincenttbk for the debugging. Could you please install version `2.1.4-beta.0` to see if that solves your issue?

**Comment by Vincenttbk** [comment]
> Thanks @Vincenttbk for the debugging. Could you please install version `2.1.4-beta.0` to see if that solves your issue?

Hi, it is working on my iOS build now. What did you changed?

**Comment by vinzscam** [comment]
ok, nice. I will make a proper release then. The library tries to dynamically calculate the presenter View Controller: this was introduced more than 2 years ago, to solve an issue with `react-native-navigation`. But for some reason like in your case (I wasn't able reproduce the issue) this process is failing. Now I've introduced a fallback.

**Comment by vinzscam** [comment]
Closed by #90. Version `2.1.4` has now been released.
