### ISSUE TITLE
On Android API 30, failing to open files

### ISSUE THREAD

**Issue by socialcode-rob1** [vinzscam/react-native-file-viewer#94]
When attempting to build and run on Android 30 emulators, I'm receiving multiple types of errors.

Build script configuration...
```
        buildToolsVersion = "30.0.3"
        minSdkVersion = 24
        compileSdkVersion = 30
        targetSdkVersion = 30
        playServicesVersion = "17.0.0"
        kotlinVersion = "1.3.72"
```

When running on an Android 29 emulator, files and docs open fine.
When running on an Android 30 emulator, error displayed....

Opening an image...

File reference used `file:///data/user/0/com.myapp/files/app/appcore/files/cloud/files/9/1237/temp778200586557997840rn_image_picker_lib_temp_5fed3c4d-0df1-4c4.jpg`

```
Error: No app associated with this mime type
    at index.js:25
    at RCTDeviceEventEmitter.emit (EventEmitter.js:189)
    at MessageQueue.__callFunction (MessageQueue.js:436)
    at MessageQueue.js:111
    at MessageQueue.__guard (MessageQueue.js:384)
    at MessageQueue.callFunctionReturnFlushedQueue (MessageQueue.js:110)
    at debuggerWorker.js:69
```

File reference used...
`file:///data/user/0/com.myapp/files/app/appcore/files/cloud/files/9/1236/temp8153285029360235510IMG_20201228_150952.jpg`

```
Error: Failed to find configured root that contains /
    at index.js:25
    at RCTDeviceEventEmitter.emit (EventEmitter.js:189)
    at MessageQueue.__callFunction (MessageQueue.js:436)
    at MessageQueue.js:111
    at MessageQueue.__guard (MessageQueue.js:384)
    at MessageQueue.callFunctionReturnFlushedQueue (MessageQueue.js:110)
    at debuggerWorker.js:69 
```

While investigating the code it seems to break on `showStoreSuggestions` returning `{NativeMap:{}}` resulting in the first error listed.

**Comment by socialcode-rob1** [comment]
My temporary fix right now is to downgrade

```
        compileSdkVersion = 29
        targetSdkVersion = 29
```

**Comment by IHsuanLu** [comment]
Try using https://github.com/ds300/patch-package to remove the `showStoreSuggestions`

**Comment by IHsuanLu** [comment]
try using https://www.npmjs.com/package/patch-package to do the following update in `RNFileViewerModule.java`, and make it redirect to Google PlayStore if there is no corresponding application to open files with certain mimeType
```
-          if (showStoreSuggestions) {
-            if(mimeType == null) {
-              throw new Exception("It wasn't possible to detect the type of the file");
-            }
-            Intent storeIntent = new Intent(Intent.ACTION_VIEW, Uri.parse("market://search?q=" + mimeType + "&c=apps"));
-            getCurrentActivity().startActivity(storeIntent);
+          if(mimeType == null) {
+            throw new Exception("It wasn't possible to detect the type of the file");
           }
-          throw new Exception("No app associated with this mime type");
+          Intent storeIntent = new Intent(Intent.ACTION_VIEW, Uri.parse("market://search?q=" + mimeType + "&c=apps"));
+          getCurrentActivity().startActivity(storeIntent);
```

**Comment by StuartCallan** [comment]
We are also encountering this issue on Android 30 only.

We don't have the option to lower our sdk versions.

Any updates on a fix for this?

**Comment by StuartCallan** [comment]
So I did some more digging, and it appears that from Android 11 (API level 30) they have introduced stricter policy on what packages an app can view on the users device.

It is all explained on the developer documentation [here](https://developer.android.com/training/basics/intents/package-visibility#top_of_page).

All previous versions of Android allowed an app to query all installed packages so this is why we don't see this issue on lower version. If you would like to mimic that functionality then you can add the [QUERY_ALL_PACKAGES](https://developer.android.com/reference/kotlin/android/Manifest.permission#query_all_packages) permission to your manifest.

It's more likely that for this library we'd like to use the <queries> approach in the manifest, as we only want to view files. To do this we can add the following in the manifest:

    <manifest package="com.example.app">
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:mimeType="*/*" />
        </intent>
    </queries>
    ...
</manifest>

If you're using the queries approach and get an error during building, then you'll probably need to update your version of gradle as mentioned [here](https://stackoverflow.com/questions/62969917/how-to-fix-unexpected-element-queries-found-in-manifest-error).

I've tested with the queries approach above and the library here is working for my use case of opening a pdf.

The longer term fix would be to add this fix to the Android manifest of this library. I may create a PR if I get around to it.

Hope this helps people!

**Comment by vinzscam** [comment]
Hi! Thanks for reporting the issue.
Yeah, the error affects devices targeting Android Api level 30+.
I've updated the [documentation](https://github.com/vinzscam/react-native-file-viewer#extra-step-android-only) regarding this issue.

**Comment by govindavashishtha** [comment]
Hi!
Performed the above changes to resolve the bug but it's not working.

`buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        googlePlayServicesAuthVersion = "19.2.0"`

React-Native version

`"react": "16.13.1",
    "react-native": "0.63.4",`


https://user-images.githubusercontent.com/57435703/147056133-ae502a39-c5d6-4cf5-85a8-1ce8665dea19.mp4
