### ISSUE TITLE
Unable to download to Gallery on Android

### ISSUE THREAD

**Issue by socialcode-rob1** [vinzscam/react-native-file-viewer#98]
The library supports Share on both iOS and Android.

Within iOS, the share option offers you a way to Save To Photos.
On Android, you can share on the cloud or social platforms, but not simply to Gallery.

Is there a way to enable Gallery as an option?

I'm considering adding a download button to the view.  Thoughts?

**Comment by Hirurgo** [comment]
import CameraRoll from '@react-native-community/cameraroll';

**Comment by vinzscam** [comment]
Hi,
unfortunately the options present on the contextual menu shown are up to the installed viewer as well as the version of Android you are running. In some devices you might have this feature out of the box.
